name: Choose runner
run-name: Chose runner ${{ inputs.chosen-os }}

on:
  workflow_dispatch:
    inputs:
      chosen-os:
        required: true
        type: choice
        options:
        - ubuntu-latest
        - ubuntu-22.04
        - ubuntu-20.04
        - macos-latest
        - macos-12
        - macos-11

        
jobs:
  test:
    runs-on: [self-hosted, "${{ inputs.chosen-os }}"]
    steps:
    - run: echo Hello world!            
